### ISSUE TITLE
Smelter Enchantment on shovel does not smelt sand to glass

### ISSUE THREAD

**Issue by k0x1a4** [nulli0n/ExcellentEnchants-spigot#36]
Is the Smelter enchantment supposed to smelt sand to glass because you can put it on all tools including the shovel and the description says it "has a chance to smelt BLOCKS/ores"?

**Comment by HandsomeRomanian** [comment]
By default in the config the plugin seems to only smelt iron and gold you have to add the other materials you want it to smelt.
Here are the ones I found:
```YML
  Smelting_Table:
    RAW_GOLD: GOLD_INGOT
    RAW_IRON: IRON_INGOT
    RAW_COPPER: COPPER_INGOT
    SAND: GLASS
    COBBLESTONE: STONE
    RED_SAND: GLASS
    CLAY_BALL: BRICK
    NETHERRACK: NETHER_BRICK
 ```
