### ISSUE TITLE
[Suggestion] Per-world settings for enchants spawning on mobs

### ISSUE THREAD

**Issue by MiddleSand** [nulli0n/ExcellentEnchants-spigot#72]
The config could look something like

```
Mob_Spawning:
    Default:
        Chance: 25.0
        Level:
            Min: -1
            Max: -1
    Worlds:
        some-specific-world:
            Chance: 25.0
            Level:
                Min: -1
                Max: -1
```

Could be a universal setting and per-enchantment. This feature lets server owners scale difficulty and enchant sets on different worlds, i.e. have the nether's mobs have certain enchants and more frequently, versus the overworld, versus mining world A, etc.
